- name: Clone yay
  git:  
    repo: 'https://aur.archlinux.org/yay.git'
    dest: /tmp/git/yay/
    
- name: Install yay
  shell: |
    cd /tmp/git/yay/ && makepkg -si --noconfirm

- name: Install ansible-aur
  shell: |
    yay -S --noconfirm ansible-aur
        
- name: Install dropbox
  aur: name=dropbox skip_installed=true skip_pgp_check=true

- name: Install sublime
  aur: name=sublime-text-dev skip_installed=true skip_pgp_check=true
