- name: "install atom"
  tags: snaps
  become: yes
  snap:
    name: atom
    classic: yes

- name: "install sublime"
  tags: snaps
  become: yes
  snap:
    name:  sublime-text
    classic: yes

- name: "install postman"
  tags: snaps
  become: yes
  snap:
    name: postman

- name: "install spotify"
  tags: snaps
  become: yes
  snap:
    name: spotify
