# based on https://docs.docker.com/install/linux/linux-postinstall/

- name: "install docker"
  tags: docker
  become: yes
  apt:
    name: docker,docker-compose
    state: present

- name: "configure docker for non-sudo use - create group docker"
  tags: docker
  become: yes
  group:
    name: docker
    state: present

- name: "configure docker for non-sudo use - add user user to group docker"
  tags: docker
  become: yes
  user:
    name: vagrant
    groups: docker
    append: yes

- name: "enable docker service"
  tags: docker
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
